### ISSUE TITLE
Possible discrepancy with the shortcut in the readme

### ISSUE THREAD

**Issue by mikeysan** [nvinayvarma189/log-booster#2]
In the Readme you have two different shortcuts, which one is correct?

In the How to Use:
![image](https://github.com/nvinayvarma189/log-booster/assets/13338176/f27a2593-8b3a-40f0-bf2b-f9955ac70294)

Then in Limitations
![image](https://github.com/nvinayvarma189/log-booster/assets/13338176/2311eb54-2285-498c-98be-851bde260b11)

Unless they do different things, in which case it should be make clearer to understand.

**Comment by nvinayvarma189** [comment]
hey @mikeysan thanks for pointing this out. It is indeed a discrepancy. I wanted to say
```
It is only accessible via the shortcut key (`ctrl+alt+l` or `cmd+alt+b`).
```

I have corrected this now
